/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 2.1.6.v20140519.
* Used org.franca.core 0.8.11.201401091023.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#ifndef COMMONAPI_ATTRIBUTES_E02_Attributes_H_
#define COMMONAPI_ATTRIBUTES_E02_Attributes_H_




#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#endif

#include <CommonAPI/types.h>

#undef COMMONAPI_INTERNAL_COMPILATION

namespace commonapi {
namespace attributes {

class E02Attributes {
 public:
    virtual ~E02Attributes() { }

    static inline const char* getInterfaceId();
    static inline CommonAPI::Version getInterfaceVersion();
};

const char* E02Attributes::getInterfaceId() {
    static const char* interfaceId = "commonapi.attributes.E02Attributes";
    return interfaceId;
}

CommonAPI::Version E02Attributes::getInterfaceVersion() {
    return CommonAPI::Version(1, 0);
}


} // namespace attributes
} // namespace commonapi

namespace CommonAPI {

}


namespace std {
    //hashes for types

    //hashes for error types
}

#endif // COMMONAPI_ATTRIBUTES_E02_Attributes_H_
