/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 2.1.6.v20140519.
* Used org.franca.core 0.8.11.201401091023.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#ifndef COMMONAPI_ATTRIBUTES_E02_Attributes_PROXY_BASE_H_
#define COMMONAPI_ATTRIBUTES_E02_Attributes_PROXY_BASE_H_

#include "E02Attributes.h"


#include <commonapi/attributes/CommonTypes.h>

#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#endif

#include <CommonAPI/InputStream.h>
#include <CommonAPI/OutputStream.h>
#include <CommonAPI/SerializableStruct.h>
#include <cstdint>
#include <string>

#include <CommonAPI/Attribute.h>
#include <CommonAPI/Proxy.h>

#undef COMMONAPI_INTERNAL_COMPILATION

namespace commonapi {
namespace attributes {

class E02AttributesProxyBase: virtual public CommonAPI::Proxy {
 public:
    typedef CommonAPI::ObservableAttribute<int32_t> XAttribute;
    typedef CommonAPI::ObservableAttribute<CommonTypes::a1Struct> A1Attribute;
    typedef CommonAPI::ObservableReadonlyAttribute<float> FAttribute;


    virtual XAttribute& getXAttribute() = 0;
    virtual A1Attribute& getA1Attribute() = 0;
    virtual FAttribute& getFAttribute() = 0;


};

} // namespace attributes
} // namespace commonapi

#endif // COMMONAPI_ATTRIBUTES_E02_Attributes_PROXY_BASE_H_
