/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 2.1.6.v20140519.
* Used org.franca.core 0.8.11.201401091023.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#ifndef COMMONAPI_EXAMPLES_E01_Hello_World_PROXY_BASE_H_
#define COMMONAPI_EXAMPLES_E01_Hello_World_PROXY_BASE_H_

#include "E01HelloWorld.h"



#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#endif

#include <vector>

#include <CommonAPI/Proxy.h>
#include <functional>
#include <future>

#undef COMMONAPI_INTERNAL_COMPILATION

namespace commonapi {
namespace examples {

class E01HelloWorldProxyBase: virtual public CommonAPI::Proxy {
 public:

    typedef std::function<void(const CommonAPI::CallStatus&, const std::string&)> SayHelloAsyncCallback;



    virtual void sayHello(const std::string& name, const int32_t& size, CommonAPI::CallStatus& callStatus, std::string& message) = 0;
    virtual std::future<CommonAPI::CallStatus> sayHelloAsync(const std::string& name, const int32_t& size, SayHelloAsyncCallback callback) = 0;
};

} // namespace examples
} // namespace commonapi

#endif // COMMONAPI_EXAMPLES_E01_Hello_World_PROXY_BASE_H_
