/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 2.1.6.v20140519.
* Used org.franca.core 0.8.11.201401091023.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#ifndef COMMONAPI_EXAMPLES_E01_Hello_World_PROXY_H_
#define COMMONAPI_EXAMPLES_E01_Hello_World_PROXY_H_

#include "E01HelloWorldProxyBase.h"


#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#endif


#undef COMMONAPI_INTERNAL_COMPILATION

namespace commonapi {
namespace examples {

template <typename ... _AttributeExtensions>
class E01HelloWorldProxy: virtual public E01HelloWorld, virtual public E01HelloWorldProxyBase
, public _AttributeExtensions... {
public:
    E01HelloWorldProxy(std::shared_ptr<CommonAPI::Proxy> delegate);
    ~E01HelloWorldProxy();

    typedef E01HelloWorld InterfaceType;




    /**
     * Calls sayHello with synchronous semantics.
     * 
    * All const parameters are input parameters to this method.
    * All non-const parameters will be filled with the returned values.
     * The CallStatus will be filled when the method returns and indicate either
     * "SUCCESS" or which type of error has occurred. In case of an error, ONLY the CallStatus
     * will be set.
     */
    virtual void sayHello(const std::string& name, const int32_t& size, CommonAPI::CallStatus& callStatus, std::string& message);
    /**
     * Calls sayHello with asynchronous semantics.
     * 
     * The provided callback will be called when the reply to this call arrives or
     * an error occurs during the call. The CallStatus will indicate either "SUCCESS"
     * or which type of error has occurred. In case of any error, ONLY the CallStatus
     * will have a defined value.
     * The std::future returned by this method will be fulfilled at arrival of the reply.
     * It will provide the same value for CallStatus as will be handed to the callback.
     */
    virtual std::future<CommonAPI::CallStatus> sayHelloAsync(const std::string& name, const int32_t& size, SayHelloAsyncCallback callback);


    /**
     * Returns the CommonAPI address of the remote partner this proxy communicates with.
     */
    virtual std::string getAddress() const;

    /**
     * Returns the domain of the remote partner this proxy communicates with.
     */
    virtual const std::string& getDomain() const;

    /** 
     * Returns the service ID of the remote partner this proxy communicates with.
     */
    virtual const std::string& getServiceId() const;

    /**
     * Returns the instance ID of the remote partner this proxy communicates with.
     */
    virtual const std::string& getInstanceId() const;

    /**
     * Returns true if the remote partner for this proxy is currently known to be available.
     */
    virtual bool isAvailable() const;

    /**
     * Returns true if the remote partner for this proxy is available.
     */
    virtual bool isAvailableBlocking() const;

    /**
     * Returns the wrapper class that is used to (de-)register for notifications about
     * the availability of the remote partner of this proxy.
     */
    virtual CommonAPI::ProxyStatusEvent& getProxyStatusEvent();

    /**
     * Returns the wrapper class that is used to access version information of the remote
     * partner of this proxy.
     */
    virtual CommonAPI::InterfaceVersionAttribute& getInterfaceVersionAttribute();

 private:
    std::shared_ptr<E01HelloWorldProxyBase> delegate_;
};

#ifdef WIN32
    typedef E01HelloWorldProxy<CommonAPI::WINDummyAttributeExtension<CommonAPI::WINDummyAttribute>> E01HelloWorldProxyDefault;
#else
    typedef E01HelloWorldProxy<> E01HelloWorldProxyDefault;
#endif


//
// E01HelloWorldProxy Implementation
//
template <typename ... _AttributeExtensions>
E01HelloWorldProxy<_AttributeExtensions...>::E01HelloWorldProxy(std::shared_ptr<CommonAPI::Proxy> delegate):
        _AttributeExtensions(*(std::dynamic_pointer_cast<E01HelloWorldProxyBase>(delegate)))...,
        delegate_(std::dynamic_pointer_cast<E01HelloWorldProxyBase>(delegate)) {
}

template <typename ... _AttributeExtensions>
E01HelloWorldProxy<_AttributeExtensions...>::~E01HelloWorldProxy() {
}

template <typename ... _AttributeExtensions>
void E01HelloWorldProxy<_AttributeExtensions...>::sayHello(const std::string& name, const int32_t& size, CommonAPI::CallStatus& callStatus, std::string& message) {
    delegate_->sayHello(name, size, callStatus, message);
}

template <typename ... _AttributeExtensions>
std::future<CommonAPI::CallStatus> E01HelloWorldProxy<_AttributeExtensions...>::sayHelloAsync(const std::string& name, const int32_t& size, SayHelloAsyncCallback callback) {
    return delegate_->sayHelloAsync(name, size, callback);
}

template <typename ... _AttributeExtensions>
std::string E01HelloWorldProxy<_AttributeExtensions...>::getAddress() const {
    return delegate_->getAddress();
}

template <typename ... _AttributeExtensions>
const std::string& E01HelloWorldProxy<_AttributeExtensions...>::getDomain() const {
    return delegate_->getDomain();
}

template <typename ... _AttributeExtensions>
const std::string& E01HelloWorldProxy<_AttributeExtensions...>::getServiceId() const {
    return delegate_->getServiceId();
}

template <typename ... _AttributeExtensions>
const std::string& E01HelloWorldProxy<_AttributeExtensions...>::getInstanceId() const {
    return delegate_->getInstanceId();
}

template <typename ... _AttributeExtensions>
bool E01HelloWorldProxy<_AttributeExtensions...>::isAvailable() const {
    return delegate_->isAvailable();
}

template <typename ... _AttributeExtensions>
bool E01HelloWorldProxy<_AttributeExtensions...>::isAvailableBlocking() const {
    return delegate_->isAvailableBlocking();
}

template <typename ... _AttributeExtensions>
CommonAPI::ProxyStatusEvent& E01HelloWorldProxy<_AttributeExtensions...>::getProxyStatusEvent() {
    return delegate_->getProxyStatusEvent();
}

template <typename ... _AttributeExtensions>
CommonAPI::InterfaceVersionAttribute& E01HelloWorldProxy<_AttributeExtensions...>::getInterfaceVersionAttribute() {
    return delegate_->getInterfaceVersionAttribute();
}


} // namespace examples
} // namespace commonapi


#endif // COMMONAPI_EXAMPLES_E01_Hello_World_PROXY_H_
