/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 2.1.6.v20140519.
* Used org.franca.core 0.8.11.201401091023.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#ifndef COMMONAPI_EXAMPLES_E01_Hello_World_H_
#define COMMONAPI_EXAMPLES_E01_Hello_World_H_




#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#endif

#include <CommonAPI/types.h>

#undef COMMONAPI_INTERNAL_COMPILATION

namespace commonapi {
namespace examples {

class E01HelloWorld {
 public:
    virtual ~E01HelloWorld() { }

    static inline const char* getInterfaceId();
    static inline CommonAPI::Version getInterfaceVersion();
};

const char* E01HelloWorld::getInterfaceId() {
    static const char* interfaceId = "commonapi.examples.E01HelloWorld";
    return interfaceId;
}

CommonAPI::Version E01HelloWorld::getInterfaceVersion() {
    return CommonAPI::Version(0, 1);
}


} // namespace examples
} // namespace commonapi

namespace CommonAPI {

}


namespace std {
    //hashes for types

    //hashes for error types
}

#endif // COMMONAPI_EXAMPLES_E01_Hello_World_H_
